# Generated by Django 4.2.2 on 2023-06-09 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='-', help_text='<small class="text-muted">уникальный</small><hr><br>', max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)], verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, default='-', help_text='<small class="text-muted">уникальный</small><hr><br>', max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)], verbose_name='ФИО')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_documents.positions')),
            ],
            options={
                'verbose_name': 'Модератор',
                'verbose_name_plural': 'Модераторы',
                'ordering': ('fio', 'position', 'id'),
            },
        ),
    ]
