# Generated by Django 4.2.2 on 2023-06-09 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderators',
            name='position',
            field=models.ForeignKey(help_text='<small class="text-muted">ForeignKey</small><hr><br>', on_delete=django.db.models.deletion.CASCADE, to='django_documents.positions', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='title',
            field=models.CharField(blank=True, default='-', help_text='<small class="text-muted">уникальный</small><hr><br>', max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)], verbose_name='Наименование должности'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='-', help_text='<small class="text-muted">уникальный</small><hr><br>', max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)], verbose_name='Заголовок')),
                ('moderator', models.ForeignKey(help_text='<small class="text-muted">ForeignKey</small><hr><br>', on_delete=django.db.models.deletion.CASCADE, to='django_documents.moderators', verbose_name='Утверждающий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title', 'moderator', 'id'),
            },
        ),
    ]
