# Generated by Django 4.2.2 on 2023-06-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_documents', '0002_alter_moderators_position_alter_positions_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='moderator',
            field=models.ForeignKey(help_text='<small class="text-muted">ForeignKey</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_documents.moderators', verbose_name='Утверждающий'),
        ),
    ]
