# Generated by Django 4.2.2 on 2023-06-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postratings',
            options={'ordering': ('-post', 'author'), 'verbose_name': 'Рейтинг к публикации', 'verbose_name_plural': 'Рейтинги к публикациям'},
        ),
        migrations.RenameField(
            model_name='postratings',
            old_name='post_id',
            new_name='post',
        ),
    ]
