# Generated by Django 4.2.5 on 2023-09-15 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.BigIntegerField(unique=True, verbose_name="Пост")),
                ("user_id", models.BigIntegerField(verbose_name="Пользователь")),
                (
                    "value",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Значение рейтинга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отметка рейтинга",
                "verbose_name_plural": "Отметки рейтинга",
                "ordering": ("post_id", "user_id"),
            },
        ),
    ]
