# Generated by Django 4.2.5 on 2023-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=2000, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ("title",),
            },
        ),
    ]
