# Generated by Django 4.2.6 on 2023-10-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0004_alter_news_options_news_datetime_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
        migrations.DeleteModel(
            name="Worker",
        ),
    ]
