# Generated by Django 4.2.3 on 2023-07-20 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mem',
            options={'ordering': ('-date_time', 'title'), 'verbose_name': 'Мем', 'verbose_name_plural': 'Мемы'},
        ),
        migrations.AlterField(
            model_name='mem',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/posts', verbose_name='Изображение')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('is_ban', models.BooleanField(default=False, verbose_name='Отключено ли отображение')),
                ('author', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-date_time', 'title'),
            },
        ),
    ]
