# Generated by Django 4.2.3 on 2023-07-20 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0002_alter_mem_options_alter_mem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Текст комментария')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('author', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('news', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='django_app.news', verbose_name='К какой новости')),
            ],
            options={
                'verbose_name': 'Комментарий к новости',
                'verbose_name_plural': 'Комментарии к новостям',
                'ordering': ('-date_time', 'news'),
            },
        ),
    ]
