# Generated by Django 4.2.2 on 2023-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
