# Generated by Django 4.2.2 on 2023-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_requests_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='client',
            field=models.CharField(blank=True, default='Аноним', help_text='<small class="text-muted">строка</small><hr><br>', max_length=200, null=True, verbose_name='Клиент'),
        ),
    ]
