# Generated by Django 4.2.2 on 2023-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_requests_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='<small class="text-muted">сумма</small><hr><br>', max_digits=12, verbose_name='Цена обращения'),
        ),
    ]
