# Generated by Django 4.2.2 on 2023-06-08 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_requests_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='<small class="text-muted">сумма</small><hr><br>', verbose_name='Цена обращения'),
        ),
    ]
