# Generated by Django 4.2.2 on 2023-06-08 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_requests_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='<small class="text-muted">сумма</small><hr><br>', verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
