# Generated by Django 4.2.2 on 2023-06-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_alter_requests_date_alter_requests_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ('-is_success', '-datetime', 'title'), 'verbose_name': 'Запрос к юристам', 'verbose_name_plural': 'Запросы к юристам'},
        ),
    ]
